services:
  fastapi:
    container_name: fastapi_dev
    build: ./backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - type: volume
        source: fastapi-files
        target: /usr/src/app/files
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /usr/src
          ignore:
            - venv/
            - .idea/
            - alembic/

        - action: rebuild
          path: ./backend/requirements.txt
  nginx:
    container_name: nginx_dev
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/nginx.dev.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: fastapi-files
        target: /usr/share/nginx/fastapi

  mongo:
    container_name: mango_dev
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hard
    volumes:
      - type: volume
        source: mangodata
        target: /data/db

  postgres:
    container_name: postgres_dev
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=hard
      - POSTGRES_USER=main
      - POSTGRES_DB=fastapi
    volumes:
      - type: volume
        source: postgresdata
        target: /var/lib/postgresql/data

volumes:
  fastapi-files:
    external: true
  mangodata:
    external: true
  postgresdata:
    external: true