services:
  nginx:
    container_name: nginx_prod
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: fastapi-files
        target: /usr/share/nginx/fastapi

  mongo:
    container_name: mango_prod
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hard
    volumes:
      - type: volume
        source: mangodata
        target: /data/db

  postgres:
    container_name: postgres_prod
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=hard
      - POSTGRES_USER=main
      - POSTGRES_DB=fastapi
    volumes:
      - type: volume
        source: postgresdata
        target: /var/lib/postgresql/data

  fastapi:
    container_name: fastapi_prod
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - type: volume
        source: fastapi-files
        target: /usr/src/app/files

    depends_on:
      - mongo
      - postgres

volumes:
  fastapi-files:
    external: true
  mangodata:
    external: true
  postgresdata:
    external: true