name: Deploy to EC2 with rsync

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync files to EC2
        run: |
          rsync -az --delete ./ ${{ secrets.EC2_HOST }}:/home/ec2-user/app

      - name: Restart app on EC2
        run: |
          ssh ${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/app
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
          EOF
