name: Deploy to EC2 with rsync

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
            echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem && chmod 400 ec2_key.pem
            

      - name: test SSH Connection
        run: ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

      - name: Rsync files to EC2
        run: |
          rsync -avz -e "ssh -i ec2_key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_HOST }}:/home/ec2-user/app --exclude '.git' --exclude 'docker-compose.dev.yml'
      - name: Restart app on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/app
            docker volume create fastapi-files && docker volume create mangodata && docker volume create postgresdata
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
          EOF
